spring:
  datasource:
    url: ${DATABASE_URL:}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  config-location: classpath:/mybatis-config.xml